### PR TITLE
Icon search by set

### LINKED ISSUE #22: Filter icons per set
It would be cool if icons could be filtered per icon set to specifically search for related icons and browser all icons from a certain set.

### PR DESCRIPTION
**Pull request by nuernbergerA**
image

---

### Filter by set

- Total count by a filtered set
- On empty search random icons from the filtered set are shown

image

---

### Filtered Results

image

---

### Mobile
image

---
Closes #22

### CODE REVIEW

**Review by driesvints — CHANGES_REQUESTED** [review]
@nuernbergerA this is really great. I did a few cleanups. Bit unfortunate that Scout can't work with local model scopes 🤔 

One thing I'm seeing though is that the dropdown doesn't look good in Safari:

Screenshot 2021-05-15 at 21 50 11

Do we need https://github.com/tailwindlabs/tailwindcss-forms for this? Think we'll need to upgrade Tailwind CSS for that maybe 🤔

**Comment by nuernbergerA** [comment]
@driesvints yeah design isn't my strength 🤣 and I don't have access to a Mac so I can't make it work in safari. Maybe someone can fix it?

**Comment by nkeena** [comment]
> @driesvints yeah design isn't my strength 🤣 and I don't have access to a Mac so I can't make it work in safari. Maybe someone can fix it?

Have you tried adding the class `appearance-none` to the select input? It removes all browser default styling. That might do the trick.

https://v1.tailwindcss.com/docs/appearance#class-reference

**Comment by driesvints** [comment]
@nkeena that did it! Thanks :)

**Comment by driesvints** [comment]
And thanks @nuernbergerA for contributing this!

**Pull request merged**
