### PR TITLE
Added country flags

### PR DESCRIPTION
**Pull request by stijnvanouplines**

### CODE REVIEW

**Comment by driesvints** [comment]
@stijnvanouplines can you maybe show a picture how this looks like in the icon search? I'm a bit afraid it'll look bad because these are very colorful icons.

**Comment by stijnvanouplines** [comment]
This is how the index page looks like: https://paste.pics/aa0d3280cdb8fa7d26ff188f5dc3c2fa
And this is how the detail page looks like: https://paste.pics/393d8a7220a1e08951383b8659b52519

**Comment by driesvints** [comment]
Super torn on this. I realize that these icons are useful (both the square and the rectangle ones) but this will mess up the look and feel of the page quite a bit imo 😔

I'll give it a go but I can't promise that I won't revert this if it doesn't sits right with me after a while. Thanks for sending this in though 👍

**Comment by stijnvanouplines** [comment]
Thanks for merging @driesvints! Perfectly fine if you would revert it later. I needed this for my own project. Hope to help others by sharing it.

**Comment by driesvints** [comment]
Hey @stijnvanouplines. I decided to revert this in the end. We tried fixing the layout a bit by adding a gray background to the icons but it seems some of these flag icons are broken and have transparent backgrounds where there should be white. So I think it's best we remove them for now. I'll leave them in the package list of the readme of Blade Icons for now. Thanks

**Comment by stijnvanouplines** [comment]
No problem, I fully understand. I fixed the issue of transparent backgrounds in [1.0.1](https://github.com/stijnvanouplines/blade-country-flags/releases/tag/1.0.1).

**Pull request merged**
