### PR TITLE
Added css.gg icons set

### PR DESCRIPTION
**Pull request by 2zt**

### CODE REVIEW

**Review by driesvints — COMMENTED** [review]
@2zt you need to run `composer require` to add the icon set to the composer.lock file

**Comment by 2zt** [comment]
> @2zt you need to run `composer require` to add the icon set to the composer.lock file

ok

**Comment by 2zt** [comment]
> @2zt you need to run `composer require` to add the icon set to the composer.lock file

I'm sorry.
Now I've added the icon set with composer require.

**Comment by swapnilsarwe** [comment]
Hey @2zt ,
I guess we already have the css.gg icon set added to the `IconSet.php`, this would be just an duplicate of the same.

```
'id' => 4,
'name' => 'css-icons',
'repository' => 'https://github.com/khatabwedaa/blade-css-icons',
'composer' => 'khatabwedaa/blade-css-icons',
```

**Comment by 2zt** [comment]
Oh, I get it. I'm really sorry.

**Pull request closed without merging**
