### PR TITLE
Devicons set added

### PR DESCRIPTION
**Pull request by swapnilsarwe**
- Added devicons set
- updated fluent-ui, simple-icons & forkawesome icon set to the latest tags with most recent icons

@driesvints - just an FYI
- the devicons set is the color icon set with predefined colors which cannot be overriden with `fill=currentColor`. Not sure if such icon set should be part of the website.

### CODE REVIEW

**Comment by nuernbergerA** [comment]
@swapnilsarwe would it be possible to maintain 2 versions for each icon?

1. a colored version as it is and postfix with `-colored`
2. remove the current color from the surrounding box and replace hex-color values with currentColor

this is just a suggestion ;)

**Comment by driesvints** [comment]
Yeah we can't add colored icons I'm afraid.. sorry

**Comment by driesvints** [comment]
Btw, feel free to send in a new pr with just the updates for the other icons.

**Comment by swapnilsarwe** [comment]
> @swapnilsarwe would it be possible to maintain 2 versions for each icon?
> 
> 1. a colored version as it is and postfix with `-colored`
> 2. remove the current color from the surrounding box and replace hex-color values with currentColor
> 
> this is just a suggestion 😉

yeh appreciate the suggestion, will see if that could be the option.

**Comment by swapnilsarwe** [comment]
> Yeah we can't add colored icons I'm afraid.. sorry

no worries.

**Pull request closed without merging**
