### PR TITLE
add icomoon icon set

### PR DESCRIPTION
**Pull request by nerdroid23**

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks!

**Comment by driesvints** [comment]
@nerdroid23 I'm seeing these icons don't support color filling. Can you update the icons to support this? Otherwise I'll need to revert this PR.

Screenshot 2021-05-27 at 10 13 35

**Comment by nerdroid23** [comment]
@driesvints sorry about that. I'll update the config file.

**Comment by nerdroid23** [comment]
@driesvints I think that everything should be working fine now

**Pull request merged**
